language: csharp
mono: none
donet: 2.1.0
jobs:
  include:
     - stage: build
       script:
       dotnet restore
       dotnet build

    - stage: deploy
      deploy:
      provider: azure_web_apps
      verbose: true
